### ISSUE TITLE
Multiple audio freeze together | Audio doesn't loop on big files

### ISSUE THREAD

**Issue by bonmas14** [alpinestudios/oogabooga#10]
Hello, today I've tried to add some bgm for my game and found some issues with audio. I've created small video to demonstrate them. https://youtu.be/zCXITjx0vXk (doesn't loop at 1:57, and other issue is just at any time of video)

So the audio player freezes when there's access to another one. And audio just doesn't loop on big files (and very small ones too).
In my code [(github)](https://github.com/bonmas14/danmaku-dungeons/tree/2c7b4fccc3f1aeda792540798e1f8d2ac1d7cead) I've added `@audio_issue` so you can find all places where i use audio, but all of this is not that different from examples.
I just setup all music and sfx in `game_late_init` and sometimes reset sfx player when its needed in `update_enemy_state` and in `update_player` (all those called from `update_game_scene` that also called from entry loop).

I was thinking that freeze is happening because i update progression factor for audio, and as it's changed audio thread starts to write samples, and rewrites them istead of mixing together. But after importing contents of video to DAW I've noticed that before my sample starts it adds small delay. That delay is not present in actual sample. And if I just cut this delay everything sounds more seamless. Now i think that setting progression factor leads to reload of  audio, (?) and it makes all audio thread to freeze.

## before:
![изображение](https://github.com/user-attachments/assets/22e997f0-14a8-42a5-ad70-948dcdd01b20)
## after cutting:
![изображение](https://github.com/user-attachments/assets/456377c7-b40f-443f-a527-5d7010b7fffb)

What about looping I dont know why, it just doesn't loop on my music/sfx. 

## Also wanted to make some feature requests. 
I would like to have volume control for audio player and gamepad support, that would be great.

**Comment by asbott** [comment]
Hey there,

I am looking into the short pauses and the looping problem.

However, for playing the impact I recommend `play_one_audio_clip()` because otherwise you need to manage a lot of audio players to be able to play several instances of the impact clip. This also works around the bug of small pauses in the audio when setting the progression factor.

**Comment by asbott** [comment]
And there is already volume control (you can set `player->volume = 0.5`)

I forgot to document this!

**Comment by bonmas14** [comment]
Hello thanks, `play_one_audio_clip` works for me. Will wait updates about looping

**Comment by asbott** [comment]
I tracked down & fixed the bugs. See a63d76c.

The "pause" in the audio was actually my wav decoder returning 4 garbage samples at the start because it was setting the file start position for the PCM frames incorrectly.

The looping issue was because when a source gets sampled by an amount of frames which perfectly aligns with source->number_of_frames, I didn't explicitly wrap around to 0 for looping players.

I'll merge this into master later today after finishing up some other things I want to get done for the next version.

Thank you for submitting the issue!

**Comment by bonmas14** [comment]
Thank you for fixing it, have a nice day!
