### ISSUE TITLE
Headers error with gcc

### ISSUE THREAD

**Issue by saponciou** [alpinestudios/oogabooga#20]
So for some reasons, i cant use clang so i need to switch to gcc, i rewrote the command in the build.bat to look like this:

`gcc -g -o cgame.exe ../build.c -O0 -std=c11 -D_CRT_SECURE_NO_WARNINGS -Wextra -Wno-deprecated-declarations -Wno-incompatible-pointer-types -Wno-type-limits -Wno-sign-compare -Wno-unused-parameter -Wno-builtin-declaration-mismatch -lkernel32 -lgdi32 -luser32 -lruntimeobject -lwinmm -ld3d11 -ldxguid -ld3dcompiler -lshlwapi -lole32 -lavrt -lksuser -ldbghelp`

but im getting this error:
`../oogabooga/gfx_interface.c:6:11: fatal error: dxgidebug.h: No such file or directory`

Do i have to install any sdk?

**Comment by asbott** [comment]
Have you installed visual studio build tools with windows SDK?

**Comment by Finxx1** [comment]
[Seems like a known thing that MinGW-W64 has issues with dxgidebug](https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/ace0463b-58e7-94e7-c57b-4348ae66c2f7%40codeweavers.com/), but if you are using MSYS2, I [found a package](https://packages.msys2.org/package/mingw-w64-x86_64-headers-git?repo=mingw64) that says it provides dxgidebug.h.

If you can't install Visual Studio, I have compiled Oogabooga in the past by using [this really nifty tool](https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977) that downloads MSVC without requiring admin and installing to Program Files. I still had to use clang though. Not sure how much effort it would be to use cl.exe instead of clang.

**Comment by asbott** [comment]
Closing this for now as @Finxx1 submitted a potential solution and OP has been inactive.
